### ISSUE TITLE
📢m2-d4 Team generator - suggestion

### ISSUE THREAD

**Issue by ubeytd** [nostam/strive-hw#2]
Working algorithm awesome job, first of all! 😎 

You are splitting names string with single space (" "), good idea.

Just be sure the user is not typing something to broke your algorithm to prevent this you should pre-process your input before the actual process (trimming, removing unwanted things..), and just put a description like 

**You should separate names with a single space**

**Comment by nostam** [comment]
Actually it can only takes 1 string as name per time so I think its commenting someone else? 😂 but many thanks 💪
